### ISSUE TITLE
Revise interface to be inline with Distributed.jl

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/K8sClusterManagers.jl#13]
Currently the `K8sClusterManager` uses this interface to spawn workers:
```julia
pids = K8sClusterManagers.addprocs_pod(2; namespace="my-namespace")
```
An interface which would be more inline with Distributed.jl would be:
```julia
pids = addprocs(K8sClusterManager(2; namespace="my-namespace"))
```

**Comment by omus** [comment]
https://docs.julialang.org/en/v1/stdlib/Distributed/#Cluster-Manager-Interface

**Comment by kolia** [comment]
The current interface is modeled after what's been done in https://github.com/JuliaParallel/ClusterManagers.jl, which includes the `addprocs(K8sClusterManager(...))` form, though I haven't been using it that way.
