### ISSUE TITLE
Docs aren't deploying

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/K8sClusterManagers.jl#64]
CI logs: https://github.com/beacon-biosignals/K8sClusterManagers.jl/runs/2470780970#step:5:36

I'm not totally sure why it's looking for that Travis stuff, but I noticed the Documenter version is 3 versions out of date, so maybe a newer one would fix it:
https://github.com/beacon-biosignals/K8sClusterManagers.jl/blob/270a59cafb328eda618a6332822e1aa755783662/docs/Project.toml#L6

**Comment by omus** [comment]
I noticed that the dev documents weren't being updated with the last push to master. I'll investigate
