### ISSUE TITLE
Stable docs still show v0.0.2

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/K8sClusterManagers.jl#74]

**Comment by christopher-dG** [comment]
I think this:

https://github.com/beacon-biosignals/K8sClusterManagers.jl/blob/d17520380d6efa00e1d5fae273df57f9e748b17e/.github/workflows/CI.yml#L3-L5

Needs to have `tags: '*'` added to it. Although @kleinschmidt had some not-fun adventures with trying to get this to work.

**Comment by omus** [comment]
#75 did fix the issue.
