### ISSUE TITLE
have tests! + test coverage > 50%

### ISSUE THREAD

**Issue by kolia** [beacon-biosignals/K8sClusterManagers.jl#8]
[k0s](https://docs.k0sproject.io/latest/k0s-single-node/) is a single executable kubernetes distro that will easily launch a working cluster locally

We could:
- make a `k0s_jll` with BinaryBuilder
- add a test dependency to it, run `k0s` in the background
- depend on [kubectl_jll](https://github.com/JuliaPackaging/Yggdrasil/pull/2247), run `kubectl proxy` in the background
- write tests that can run locally

**Comment by omus** [comment]
I'm still getting up to speed on Kubernetes and various tooling but I found a decent article comparing [`minikube` / `kind` / `k3s`](https://brennerm.github.io/posts/minikube-vs-kind-vs-k3s.html) and another comparing [`k3s` / `k0s`](https://saiyampathak.medium.com/k0s-yet-another-kubernetes-distro-7201ea425165). Quick summary is that `k0s` is the newest kid on the block and should have the best startup time (nice for testing).

I'll probably do some testing with all four of these options just to try it out but I'm expecting `k0s` to be preferred distro.

**Comment by omus** [comment]
It appears that `k3s` and `k0s` are intended to be run on Linux systems ([`k3s`](https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#operating-systems), [`k0s`](https://docs.k0sproject.io/latest/install/#prerequisites)). However, both `k3s` and `k0s` do have ways of running themselves inside of Docker containers which opens up the operating systems they support ([`k3s`](https://k3d.io/), [`k0s`](https://docs.k0sproject.io/latest/k0s-in-docker/)).

**Comment by omus** [comment]
I've set up the Kubernetes local tests to allow for any local Kubernetes cluster to be used. The CI is tested with minikube at the moment which can always be revisited in the future.

**Comment by omus** [comment]
Broke the 50% test coverage barrier with: https://github.com/beacon-biosignals/K8sClusterManagers.jl/commit/f4788d4fa2a33f48fa542c1f86678325f46cbfba
