### ISSUE TITLE
Cluster Tests CI job appears broken

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/K8sClusterManagers.jl#82]
First noticed in #81

**Comment by omus** [comment]
For the record the failure noticed was:
```
...
     Testing Running tests...
[ Info: Creating pod test-pod-control-named-lgjnp
[ Info: Waiting for pod to start...
Error: The operation was canceled.
```
The reason the operation was cancelled was because the job had run for `6h 0m 13s`

**Comment by ericphanson** [comment]
We should add timeouts like https://github.com/ericphanson/TrackingTimers.jl/blob/2be995fedf780796a8be7e8c8b260249963856ea/.github/workflows/CI.yml#L13 so it errors quicker if there’s a hang.
